### ISSUE TITLE
Using an array for query parameters

### ISSUE THREAD

**Issue by szepeviktor** [Setono/google-analytics-measurement-protocol#2]
@loevgaard Please consider using one `array<string, string>` for query parameters.
Mangling objects may not be the nicest thing in the world.

**Comment by loevgaard** [comment]
Not sure what you mean here? Can you elaborate? :)

**Comment by szepeviktor** [comment]
Instead of adding arbitrary `$this->$propery` to objects have one `$this->queryParameters` array.
Objects should be sovereign.

**Comment by loevgaard** [comment]
I am only using the `$this->{$property}` inside the actual class. A place where I know what the properties are, so I see no dangers there.

**Comment by loevgaard** [comment]
Also I have type safety when using actual properties instead of having an array :)
