### ISSUE TITLE
Namespace for tests

### ISSUE THREAD

**Issue by szepeviktor** [Setono/google-analytics-measurement-protocol#3]
Please add `\Test` for tests.

**Comment by loevgaard** [comment]
Can you elaborate on why you want this, @szepeviktor? :)

**Comment by szepeviktor** [comment]
I am unable.
All I see is tests are tests, so let's name them `Test`.

**Comment by loevgaard** [comment]
The files in the `tests` dir are only autoloaded in dev mode, so I see no reason to add the namespace
